name: Build and test

# TODO Change this to run on push once GH Actions is supported.
on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: make build-all MVN_FLAGS=-B -e
      - name: Run tests
        run: make test MVN_FLAGS=-B -e
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
